### ISSUE TITLE
immune system pathway from batch search results...

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#167] opened 2017-07-25 19:58 UTC
...does not seem to load on google chrome or firefox or safari.

On the other hand, http://targetvalidation.org/summary?pathway=R-HSA-168256&pathway-target=ICAM1&pathway-target=CARD9&pathway-target=ITGA4&pathway-target=ERAP2&pathway-target=IFIH1&pathway-target=IL18RAP&pathway-target=ITGAL&pathway-target=IL23R&pathway-target=IL10&pathway-target=PTPN22&pathway-target=TNFSF8&pathway-target=FCGR2A&pathway-target=ADCY7&pathway-target=TYK2&pathway-target=IL2RA&pathway-target=NOD2&pathway-target=PLCG2

loads just fine:
<img width="1043" alt="screen shot 2017-07-25 at 20 57 33" src="https://user-images.githubusercontent.com/6472381/28590948-edb942cc-717b-11e7-9cf5-24ae654e6487.png">

**Comment by deniseOme** [comment] 2017-07-25 19:59
This is the list of targets:


ADCY7
ATG16L1
CARD9
CD6
ERAP2
FCGR2A
FUT2
ICAM1
IFIH1
IL10
IL18RAP
IL23R
IL2RA
ITGA4
ITGAL
ITGB8
MST1
NOD2
NXPE1
PLCG2
PTPN22
SLAMF8
SMAD3
SP140
TNFSF8
TYK2

**Comment by deniseOme** [comment] 2017-07-25 20:13
One of the drugs does not load the image on the right side e.g.

http://staging.targetvalidation.org/summary?drug=CHEMBL1201438
<img width="988" alt="screen shot 2017-07-25 at 21 06 39" src="https://user-images.githubusercontent.com/6472381/28591323-369e3406-717d-11e7-9663-f751d02d515b.png">

This one is ok:
http://staging.targetvalidation.org/summary?drug=CHEMBL1201605
<img width="985" alt="screen shot 2017-07-25 at 21 06 44" src="https://user-images.githubusercontent.com/6472381/28591317-31afacea-717d-11e7-9649-b5fa5dbd3a91.png">

**Comment by iandunham** [comment] 2017-07-26 08:58
BTW that pathway diagram in the page doesn't display properly for
      me in safari
    
    
    
    
    On 25/07/2017 20:58, deniseOme wrote:
    
    
      ...does not seem to load on google chrome or firefox or safari.
      On the other hand, http://targetvalidation.org/summary?pathway=R-HSA-168256&pathway-target=ICAM1&pathway-target=CARD9&pathway-target=ITGA4&pathway-target=ERAP2&pathway-target=IFIH1&pathway-target=IL18RAP&pathway-target=ITGAL&pathway-target=IL23R&pathway-target=IL10&pathway-target=PTPN22&pathway-target=TNFSF8&pathway-target=FCGR2A&pathway-target=ADCY7&pathway-target=TYK2&pathway-target=IL2RA&pathway-target=NOD2&pathway-target=PLCG2
      loads just fine:
        
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/opentargets/webapp","title":"opentargets/webapp","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/opentargets/webapp"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"immune system pathway from batch search results... (#167)"}],"action":{"name":"View Issue","url":"https://github.com/opentargets/webapp/issues/167"}}}
    
    
    -- 
Cheers
Ian

Ian Dunham M.A. D.Phil
Scientific Director
Open Targets
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom 

Tel:  01223 492636  FAX:  01223 494468
dunham@ebi.ac.uk

http://targetvalidation.org
http://opentargets.org
http://twitter.com @DunhamReal

**Comment by emepyc** [comment] 2017-07-26 22:29
1) I can't replicate the problem of the immune system pathway not loading from batch search. Can you please check again and see if it doesn't load for you? If so, please specify the path you have followed.

2) The problem with drug images not loading is a problem in chembl. We take the images directly from chembl, see for example: https://www.ebi.ac.uk/chembl/api/data/image/CHEMBL3137308. But for that drug chembl doesn't provide a structure: https://www.ebi.ac.uk/chembl/api/data/image/CHEMBL1201438

3) The Safari problem with the new reactome cartoons is known. I thought it was coming from the reactome widget but it seems that the widget loads fine in Safari. My guess right now is some kind of incompatibility with Bootstrap. I'll need to investigate

**Comment by iandunham** [comment] 2017-07-27 09:21
It loads now in production. Still black though :-(
    
    
    On 26/07/2017 23:29, Miguel Pignatelli
      wrote:
    
    
      
        
          I can't replicate the problem of the immune system pathway
            not loading from batch search. Can you please check again
            and see if it doesn't load for you? If so, please specify
            the path you have followed.
        
        
          The problem with drug images not loading is a problem in
            chembl. We take the images directly from chembl, see for
            example: https://www.ebi.ac.uk/chembl/api/data/image/CHEMBL3137308.
            But for that drug chembl doesn't provide a structure: https://www.ebi.ac.uk/chembl/api/data/image/CHEMBL1201438
        
        
          The Safari problem with the new reactome cartoons is known.
            I thought it was coming from the reactome widget but it
            seems that the widget loads fine in Safari. My guess right
            now is some kind of incompatibility with Bootstrap. I'll
            need to investigate
        
      
      —
        You are receiving this because you commented.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/opentargets/webapp","title":"opentargets/webapp","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/opentargets/webapp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@emepyc in #167: 1) I can't replicate the problem of the immune system pathway not loading from batch search. Can you please check again and see if it doesn't load for you? If so, please specify the path you have followed.\r\n\r\n2) The problem with drug images not loading is a problem in chembl. We take the images directly from chembl, see for example: https://www.ebi.ac.uk/chembl/api/data/image/CHEMBL3137308. But for that drug chembl doesn't provide a structure: https://www.ebi.ac.uk/chembl/api/data/image/CHEMBL1201438\r\n\r\n3) The Safari problem with the new reactome cartoons is known. I thought it was coming from the reactome widget but it seems that the widget loads fine in Safari. My guess right now is some kind of incompatibility with Bootstrap. I'll need to investigate"}],"action":{"name":"View Issue","url":"https://github.com/opentargets/webapp/issues/167#issuecomment-318201568"}}}

**Comment by LucaFumis** [comment] 2017-07-27 11:33
Regarding the issues of black backgrounds/fills in Safari:
had a very quick look and it seems to me it could be related to the way of referencing the fill of svg elements using `url(#id)`? passing a regular colour value seems to work...

**Comment by emepyc** [comment] 2017-07-27 11:42
But it displays correctly in Safari in the widget example page:
http://reactome.org/pages/documentation/developer-guide/diagram/diagram-js/
This is why I guess there is some kind of incompatibility with the CSS we
use in our site.
A quick look at the rules applied to the widget in the dev tools doesn't
give much information.
I would try to debug not loading our CSS or components and see where the
problem reproduces.

**Comment by peatroot** [comment] 2017-07-28 09:51
As Luca says, the issue appears to be that the reactome widget uses relative urls for some of the svg element fills. For example, some elements in the svg use class 'cls-8', which specifies 'fill: url(#radial-gradient-2);'.

These are confused within the version embedded in opentargets because we use a <base href="/"> tag, whereas they don't. The base element appears to have been added in this [commit](https://github.com/opentargets/webapp/commit/e4548d62c85c28e475ac1955dbf478333ce94dca).

**Comment by emepyc** [comment] 2017-10-20 15:28
This is partially fixed now, which means that in Safari we load the old diagrams. Reactome hasn't found a better way to deal with this issue.

**Closed by emepyc** 2017-10-20 15:28 UTC
