### ISSUE TITLE
html characters in description of pathways

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/webapp#111] opened 2017-04-11 12:13 UTC
The description of some pathways has html characters such as <br> and <p>. 

See e.g.:
Major pathway of rRNA processing in the nucleolus and cytosol
https://www.targetvalidation.org/summary?pathway=R-HSA-6791226

![screen shot 2017-04-11 at 13 12 31](https://cloud.githubusercontent.com/assets/20280139/24908621/8ecec50e-1eb8-11e7-940e-bf6d6f70fd64.png)

**Comment by peatroot** [comment] 2018-01-31 11:42
This is a data issue, as the `<br>` tag is part of the API response. At @mkarmona, do you know if this is intentional? If not, suggest we close this and raise on `data_pipeline`.

**Comment by mkarmona** [comment] 2018-01-31 14:16
@peatroot help me to understand where that information is coming from. reactome index doesn't contain that prose. Perhaps, this is coming from the API and injecting it from other resources. I will have a look into that

**Comment by peatroot** [comment] 2018-01-31 20:10
Sorry @mkarmona @ckongEbi, no need to look further. Having just checked the link above, the `<br>` tags rendered correctly in Chrome for me, so perhaps something in the `webapp` has fixed this since the issue was first raised. The `<br>` tags are present in the API response, but it's a response from Reactome, so not our fault anyway. Closing as not reproducible.

**Closed by peatroot** 2018-01-31 20:10 UTC
Labels: area/web/batchsearch, enhancement, priority/backlog
