### ISSUE TITLE
On discarding uploaded target list in disease associations page, target table does not update

### ISSUE THREAD

**Issue by peatroot** [opentargets/webapp#236] opened 2018-01-16 10:24 UTC
### Observed behaviour
There are over 2000 targets associated with asthma. After uploading a list of 36 targets, the table displays just these 36. However, when the target list is cancelled, the table continues to display 36 targets and does not revert to 2000.

### Expected behaviour
Cancelling target list usage should revert to previous state.

### Environment
* Version: 3.4.4
* Browser: Chrome

**Comment by LucaFumis** [comment] 2018-06-25 10:47
I can't reproduce this at present: all appears to be working correctly in production. 
Marking as fixed.

**Closed** 2018-06-26 17:16 UTC
Labels: Kind: Bug, Priority: Low, Status: Fixed
