### ISSUE TITLE
summary pic of the URL in social media

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#141] opened 2017-06-19 08:46 UTC
When pasting the link http://targetvalidation.org/summary?drug=CHEMBL317052 on social media, we get the blue image of Open Targets Platform.

<img width="368" alt="screen shot 2017-06-19 at 09 41 47" src="https://user-images.githubusercontent.com/6472381/27276738-ff7586c0-54d3-11e7-963a-e30bcc91d548.png">

Any chance to have the actual page displayed instead, something more appealing to the eye such as:

<img width="806" alt="screen shot 2017-06-19 at 09 20 58" src="https://user-images.githubusercontent.com/6472381/27276765-1ad662cc-54d4-11e7-87dc-aa66802585d9.png">

**Comment by LucaFumis** [comment] 2017-06-29 14:40
I agree - a small preview of the actual page would be much better.
The problem is that this is a single-page-app, and as such rendered via javascript: 
social media crawlers don't run that javascript, hence the need for a "fixed" preview image.
Would need to explore some options, which might not be so straightforward...

**Comment by deniseOme** [comment] 2017-06-29 14:43
Don't worry then.
Thanks for getting back...

**Comment by LucaFumis** [comment] 2017-10-25 11:28
I've investigated this a little further. 
There are 3rd party services to do this, but it's also something offered by Netlify. 
I'll have a look at the latter with Andrea and/or Eliseo and see what they think.

A little temporary improvement could also be to make the image square and smaller so the preview is a bit more compact (with image on the right hand side)

**Comment by deniseOme** [comment] 2017-10-25 12:33
Thanks for looking into this. It's not an urgent thing. I've been now including the URL and adding the image manually as a work round...It works just fine.

**Comment by peatroot** [comment] 2018-01-31 12:49
The way most of these services work is by creating static versions of all the pages. This might not be unreasonable for target and disease profile/associations pages, but evidence pages would have to cover millions of combinations. Closing as unfeasible.

**Closed by peatroot** 2018-01-31 12:49 UTC
Labels: wontfix
